import "./globals.css";
import { Inter } from "next/font/google";
import { NextRequest } from "next/server";
import {GET} from "@/app/api/posts/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  /**
   * since we are on the server, the GET method can be called like a reguler
   * function so long we are passing it a proper NextRequest object
   */
  GET(new NextRequest(`${process.env.NEXT_PUBLIC_BASE_URL}api/posts/`));

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
